@baseUrl = http://localhost:3333
#@token = {{authenticate.response.body.access_token}}

###

# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Rodrigo Bighetti",
  "email": "rodrigo1@stack2u.net",
  "whatsapp": "+55 19 999828057",
  "password": "P@ssW0rd",
  "id_profile": "4dd8b1a6-94fa-41a7-a01c-20f2b6444dd5"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "admin@stack2u.net",
  "password": "P@ssW0rd"
}

###

# @name forgotPassword
POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
  "email": "admin@stack2u.net"
}